#!/bin/bash

BOOT_ENTRIES_DIR=${BOOT_ENTRIES_DIR:-"loader/entries"}
#  parsing function for list function
#  arguments :
#  local file="$1"  where to look
#  local by_kernel="$2" for what kernel
#  local by_title="$3" for what title
#  look for values title,version,linux,sortKey in file
#  return file_name: title (version,linux) sortKey

parsing_conf() {
    local file="$1"
    local by_kernel="$2"
    local by_title="$3"
    local title=$(grep "^title[[:space:]]*" "$file" | sed 's/^title[[:space:]]*//' | tail -n 1)
    local version=$(grep "^version[[:space:]]*" "$file" | sed 's/^version[[:space:]]*//' | tail -n 1)
    local linux=$(grep "^linux[[:space:]]*" "$file" | sed 's/^linux[[:space:]]*//' | tail -n 1)
    local sortKey=$(grep "^sort-key[[:space:]]*" "$file" | sed 's/^sort-key[[:space:]]*//' | tail -n 1)
    if [[ -n "$by_kernel" ]] && ! [[ "$linux" =~ $by_kernel ]]; then
        return 1
    fi

    if [[ -n "$by_title" ]] && ! [[ "$title" =~ $by_title ]]; then
        return 1
    fi
    if [[ -z "$title" || -z "$version" || -z "$linux" ]]; then
        echo "Error: $file does not have all required keys (title, version, linux)" >&2
        return 1
    fi
    echo "$file:$title ($version, $linux):$sortKey"
}
if false; then
    check current default directory
fi
check_dir() {
    if [[ -z "$BOOT_ENTRIES_DIR" ]]; then
        echo "Error: BOOT_ENTRIES_DIR is not defined" >&2
        return 1
    fi

    if [[ ! -d "$BOOT_ENTRIES_DIR" ]]; then
        echo "the directory doenst exist: $BOOT_ENTRIES_DIR"
    fi
}
#  arguments :
#  f) sort by name of file
#  s) sort by sortkey or file
#  k) by_kernel looking for specific kernel
#  t) by_title looking for specific title
#  handle input parametrs with getopts
#  call read func put the files in tmp_array
#  if sort_name true just sort the file
#  call parsing func give there argument by_kernel by_title
#  if sort_key true grap sortkey and filename if we dont have sortkey
#  it append zzz to be sortKey to put at end and sort it be sortKey and after that by file_name
#  in the end it print without filename and sortkey

list_entries() {
    local sort_name=false
    local sort_key=false
    local by_kernel=""
    local by_title=""
    while getopts ":sfk:t:" opt; do
        case $opt in
            f) sort_name=true ;;
            s) sort_key=true ;;
            k) by_kernel="$OPTARG" ;;
            t) by_title="$OPTARG" ;;
            :) echo "chyba: přepínač -$optarg vyžaduje argument" >&2; return 1 ;;
            \?) echo "error : wrong input: -$optarg" >&2; return 1;;
        esac
    done
    if [ $# -gt $((OPTIND - 1)) ]; then
            echo "Chyba: Neočekávaný argument: ${@:$OPTIND}" >&2
            return 1
    fi
    shift $((OPTIND - 1))
    mapfile -t file_array < <(reading_dir)
    if [[ "$sort_name" = "true" ]]; then
      file_array=($(printf "%s\n" "${file_array[@]}" | sort))
    fi
    local data_array=()
    for i in "${file_array[@]}";do
        if [[ -e "$i" ]]; then
            local result=$(parsing_conf "$i" "$by_kernel" "$by_title")
            if [[ $? -ne 0 ]]; then
                echo "error in parsing_func">&2
            else
                data_array+=("$result")
            fi
        else
            echo "something goes wrong with '$i'" >&2
        fi
    done
    if [[ "$sort_key" = "true" ]]; then
        local tmp_array=()
        for entry in "${data_array[@]}";do
            local sortKey=$(echo "$entry" | awk -F ':' '{print $NF}')
            local filename=$(echo "$entry" | awk -F ':' '{print $1}')
            if [[ -z $sortKey ]];then
                local sort_key="zzz:$(basename "$filename")"
            else
                local sort_key="$sortKey"
            fi
            tmp_array+=("$sort_key|$entry")

        done
        IFS=$'\n' sorted=($(printf "%s\n" "${tmp_array[@]}" | sort -t '|' -k1,1))
        data_array=()
        for item in "${sorted[@]}";do
            data_array+=("${item#*|}")
        done
        for i in "${data_array[@]}";do
            if [[ -n "$i" ]];then
                entry="${i#*:}"
                entry="${entry%:*}"
                echo "$entry"
            fi
        done
        return 0
    fi
        for i in "${data_array[@]}";do
            if [[ -n "$i" ]];then
                entry="${i#*:}"
                entry="${entry%:*}"
                echo "$entry"
            fi
        done
    return 0
}
#    just func that read the directory and return array with them
#    and it call reading dir also for check_dir
reading_dir(){
    check_dir "$BOOT_ENTRIES_DIR"
    local file_array=()
    for i in "$BOOT_ENTRIES_DIR"/*.conf;do
        if [[ -e "$i" ]]; then
            file_array+=("$i")
        else
            echo "error in reading dir"
            return 1
        fi
    done
    if [ ${#file_array[@]} -eq 0 ]; then
            echo "No .conf files found in $BOOT_ENTRIES_DIR." >&2
            return 1
        fi
    printf '%s\n' "${file_array[@]}"
}
#    arguments: title
#    call parsing func for parse the files
#    base on result it remove the files
remove_entry() {
    local by_title="$1"
    mapfile -t file_array < <(reading_dir)
    for i in "${file_array[@]}";do
        if [[ -e "$i" ]]; then
            local result=$(parsing_conf "$i" "$by_kernel" "$by_title")
            if [[ $? -ne 0 ]]; then
                echo "error in parsing_func">&2
            else
                data_array+=("$result")
            fi
        else
            echo "something goes wrong with '$i'" >&2
        fi
    done
    for entry in "${data_array[@]}"; do
        if [[ -n "$entry" ]];then
            local filename=$(echo "$entry" | awk -F ':' '{print $1}')
            echo "$filename"
            rm "$filename"
            echo "Removed file: $filename"
        fi
    done
}
#    func for changing a kernel command to add and to Removed
#    first and convert orig and new to add command to arrays
#    mod 1 is adding the command so it will loop if it match it will skip
#    mod 2 for removing if it match it will remove it
kernel_cmd() {
    local orig_cmd="$1"
    local mod="$2"
    local params_to_add="${3:-}"
    IFS=' ' read -ra orig_params <<< "$orig_cmd"
    IFS=' ' read -ra new_params <<< "$params_to_add"
    if [[ "$mod" = 1 ]]; then
        for par in "${new_params[@]}"; do
            found=false
            for existing in "${orig_params[@]}"; do
                if [[ "$existing" == "$par" ]]; then
                    found=true
                    break
                fi
            done
            if [ "$found" = false ]; then
                orig_params+=("$par")
            fi
        done
    fi
    if [[ "$mod" = 2 ]];then
        for par in "${new_params[@]}";do
            local filtered_params=()
            for existing in "${orig_params[@]}";do
                if [[ "$existing" == "$par" || "$existing" == "$par"=* ]]; then
                   continue
                fi
            filtered_params+=("$existing")
            done
            orig_params=("${filtered_params[@]}")
        done
    fi
    echo "${orig_params[*]}"
}
#    func that duplicate files base on some parametrs
#    arguments:
#    by_kernel="" what kernel we want
#    by_title="" what title it should have
#    by_initrd="" what initrd it should have
#    destination="" where to add
#    cmdline_add="" what file what command line to add
#    cmdline_remove="" what command to remove
#    file="" from which file to copy if it blank it find vut_defauld y
#    use while loop with case instead of getopts to make sure the execution of flag is correct

duplicate_entry() {
    local by_kernel="" by_title="" by_initrd="" destination=""
    local cmdline_add="" cmdline_remove="" file=""
    local operation=()
    local last_arg="${@: -1}"
    echo "$last_arg"
    if [[ $# -gt 0 && "$last_arg" != -* && -f "$last_arg" ]]; then
        file="$last_arg"
    set -- "${@:1:$#-1}"  #take all argument that are given us and remove the last one if it file so
                          #it doesnt mess up while loop with case inside of it
    fi
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --make-default)
                operation+=("make_default")
                shift 1
                ;;
            -k)
                operation+=("kernel $2")
                shift 2
                ;;
            -t)
                operation+=("title $2")
                shift 2
                ;;
            -i)
                operation+=("initrd $2")
                shift 2
                ;;
            -d)
           if [[ $# -ge 2 && "$2" != -* ]]; then
                    destination="$2"
                    shift 2
                elif [[ -n "$last_arg" ]]; then
                    destination="$last_arg"
                    shift 1
                else
                    echo "Error: No valid destination specified for -d."
                    exit 1
                fi
               ;;
            -a)
                operation+=("cmdline_add $2")
                shift 2
                ;;
            -r)
                operation+=("cmdline_remove $2")
                shift 2
                ;;
            *)
                echo "Invalid option: $1" >&2
                return 1
                ;;
        esac
    done
    if [[ -z "$file" || -n "$destination" ]]; then
        mapfile -t file_array < <(reading_dir)
        if [[ ${#file_array[@]} -eq 0 ]]; then
            echo "Chyba: Žádné soubory nenalezeny." >&2
            return 1
        fi

        default_found=false
        for i in "${file_array[@]}"; do
            if [[ ! -f "$i" ]]; then
                echo "Varování: '$i' není soubor. Přeskočeno." >&2
                continue
            fi
            vut_default=$(awk '/^vutfit_default[[:space:]]+/ {print $2; exit}' "$i")
            if [[ "$vut_default" == "y" ]]; then
                default_found=true
                file="$i"
                break
            fi
        done
        if ! $default_found; then
            echo "Varování: Žádný výchozí soubor nebyl nalezen." >&2
            return 1
        fi
    fi

    if [[ ! -f "$file" ]]; then
        echo "Chyba: Soubor '$file' neexistuje nebo není regulérní soubor." >&2
        return 1
    fi
    #maeking new copy append *1 to it
    original_file="$file"
    new_file="${file%.*}1.${file##*.}"
    echo "$destination"
    if ! [[ -n "$destination" ]];then
    cp "$original_file" "$new_file"
    destination="$new_file"
    fi

    local content modified_content
    if [[ ! -f "$new_file" ]];then
        content=$(<"$original_file")
    else
        content=$(<"$new_file")
    fi
    set -x

    modified_content=$(echo "$content" | sed 's/^vutfit_default y$/vutfit_default n/')
    set +x
    set +x

    #reading the array to execute the flags
    for op in "${operation[@]}";do
        case $op in
            kernel*)
                local kernel_version="${op#kernel }"
                modified_content=$(sed "s/^\(linux[[:space:]]\+\).*/\1$kernel_version/" <<< "$modified_content")
                ;;
            title*)
                local new_title="${op#title }"
                modified_content=$(sed "s/^\(title[[:space:]]\+\).*/\1$new_title/" <<< "$modified_content")
                ;;
            initrd*)
                local new_initrd="${op#initrd }" #it remove last initrd from start to to put to file
                modified_content=$(sed "s/^\(initrd[[:space:]]\+\).*/\1$new_initrd/" <<< "$modified_content")
                ;;
            #first we parse it origin cmd and after that get new cmd form kernel_cmd funct and put it back to modified_content
            cmdline_add*)
                local cmdline_add="${op#cmdline_add}"
                local origin_cmd=$(awk '/^options[[:space:]]+/ {$1=""; print substr($0,2)}' <<< "$modified_content")
                local new_cmd=$(kernel_cmd "$origin_cmd" 1 "$cmdline_add")
                modified_content=$(awk '{if ($1 == "options") { $0 = "options " new_cmd} print}' new_cmd="$new_cmd" <<< "$modified_content")
                ;;

            cmdline_remove*)
                local cmdline_remove="${op#cmdline_remove}"
                local origin_cmd=$(awk '/^options[[:space:]]+/ {$1=""; print substr($0,2)}' <<< "$modified_content")
                local new_cmd=$(kernel_cmd "$origin_cmd" 2 "$cmdline_remove")
                modified_content=$(awk '{if ($1 == "options") { $0 = "options " new_cmd} print}' new_cmd="$new_cmd" <<< "$modified_content")
                ;;
               esac

           done
           #print modified_content to destination
    echo "$modified_content" > "$destination"
    if [[ " ${operation[*]} " =~ " make_default " ]]; then
        make_default "$destination"
    fi

}
#    we get file that has vut_defualt y
#    and print it
show_default() {
    local local_f_par=false
    local by_kernel=""
    local by_title=""
    local num_vit=0
    mapfile -t file_array < <(reading_dir)
    while getopts ":f" opt; do
        case $opt in
            f) local_f_par=true ;;
            :) echo "chyba: přepínač -$optarg vyžaduje argument" >&2; return 1 ;;
            \?) echo "error : wrong input: -$optarg" >&2; return 1;;
        esac
    done
    if [ $# -gt $((OPTIND - 1)) ]; then
            echo "Chyba: Neočekávaný argument: ${@:$OPTIND}" >&2
            return 1
    fi
    shift $((OPTIND - 1))
    for i in "${file_array[@]}"; do
       if [[ -e "$i" ]]; then
         local vut_default=$(grep -m 1 "^vutfit_default[[:space:]]*" "$i" | sed 's/^vutfit_default[[:space:]]*//')
         if [[ "$vut_default" == "y" ]]; then
           default_found=true
           default_file="$i"
           break
         fi
       else
         echo "Chyba: Soubor '$i' neexistuje." >&2
         return 1
       fi
     done
     if "$default_found"; then
         if "$local_f_par"; then
           echo "$default_file"
         else
           cat "$default_file"
         fi
         return 0
    else
        echo "Chyba: Žádná výchozí položka nebyla nalezena." >&2
        return 1
    fi
}
#    we make file that is given like argument vut_defauld y and others in directory vut default n
make_default() {
    local file="$1"
    if [[ -z "$file" ]]; then
        echo "Chyba: Je nutné zadat cestu k souboru." >&2
        return 1
    fi
    if [[ -f "$file" && -s "$file" ]]; then
        if grep -q '^vutfit_default\s' "$file"; then
            sed -i 's/^vutfit_default\s.*/vutfit_default y/' "$file"
        else
            echo "vutfit_default y" >> "$file"
        fi
    else
        echo "creating file"
        > "$file"
        for i in {1..5}; do
            echo >> "$file"
        done
        echo "vutfit_default y" >> "$file"
    fi
    if ! grep -q '^vutfit_default y' "$file"; then
        echo "Chyba: Nastavení výchozí položky selhalo" >&2
        return 1
    fi
    mapfile -t file_array < <(reading_dir)
    for i in "${file_array[@]}"; do
        if [[ "$(basename "$i")" == "$(basename "$file")" ]]; then
                continue
        fi
       if [[ -e "$i" ]]; then
           vut_default=$(awk '/^vutfit_default[ \t]/ {print $2; exit}' "$i")
         if [[ "$vut_default" == "y" ]]; then
             echo "hello $i"
           sed -i 's/^vutfit_default\s.*/vutfit_default n/' "$i"
           default_found=true
           break
         fi
       else
         echo "Chyba: Soubor '$i' neexistuje." >&2
         return 1
       fi
     done
    echo "vut_defualt is in $file"
}
#    changing a default directory

default_dir() {
    local directory="$1"
    local path_to_dir=$(realpath -m "$directory" 2>/dev/null)
    if [[ -z "$path_to_dir" ]]; then
        echo "Error: Directory not specified" >&2
        return 1
    fi

    if [[ ! -d "$path_to_dir" ]]; then
        if ! mkdir -p "$path_to_dir"; then
            echo "Error: Failed to create directory '$directory'" >&2
            return 1
        fi
        echo "Directory created: $path_to_dir"
    fi
    echo "$path_to_dir"
    BOOT_ENTRIES_DIR="$path_to_dir"
    echo "new directory $BOOT_ENTRIES_DIR"
}
if [ "$1" == "-b" ];then
    shift
    default_dir "$1"
    shift
fi
# Main logic for parsing arguments
case "$1" in
  list)
      shift
      list_entries "$@"
      ;;
  remove)
      shift
      remove_entry "$@"
      ;;
  duplicate)
      shift
      echo "hello"
      duplicate_entry "$@"
      ;;
  show-default)
      shift
      show_default "$@"
      ;;
  --make-default)
      shift
      make_default "$@"
      ;;
  *)
      echo "Neznámý příkaz: $1"
      exit 1
      ;;
esac

exit 0
